### ISSUE TITLE
Criar um formulario de contato

### ISSUE THREAD

**Issue by alessandrofeitoza** [iwtrainingbr/site-projeto-front-09#2]
## Descrição
Após a section da galeria, mostrar um formulario de contato ocupando metade da tela, a metade do lado direito.

Campos necessários:
- nome
- email
- telefone
- Mensagem (texto longo)

**Comment by FelipeDeBoa** [comment]
![image](https://user-images.githubusercontent.com/53651862/124386226-d4a67b80-dcaf-11eb-8e6e-42f48b8a4587.png)

**Comment by alessandrofeitoza** [comment]
Resolvido pelo @FelipeDeBoa
